export const CONSTANT_TYPES = {
  CAKE_ORDERED: "CAKE_ORDERED",
  ICE_CREAM_ORDERED: "ICE_CREAM_ORDERED",
  FETCH_USER_REQUEST: "FETCH_USER_REQUEST",
  FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
  FETCH_USER_ERROR: "FETCH_USER_ERROR",
};
